// const SampleDeck = {
//     [ 1, 'espada' ]: 1,
//     [ 1, 'basto' ]: 2,
//     [ 7, 'espada' ]: 3,
//     [ 7, 'oro' ]: 4,
//     [ 3, 'espada' ]: 5,
//     [ 3, 'basto' ]: 5,
//     [ 3, 'oro' ]: 5,
//     [ 3, 'copa' ]: 5,
//     [ 2, 'espada' ]: 6,
//     [ 2, 'basto' ]: 6,
//     [ 2, 'oro' ]: 6,
//     [ 2, 'copa' ]: 6,
//     [ 1, 'oro' ]: 7,
//     [ 1, 'copa' ]: 7,
//     [ 12, 'espada' ]: 8,
//     [ 12, 'basto' ]: 8,
//     [ 12, 'oro' ]: 8,
//     [ 12, 'copa' ]: 8,
//     [ 11, 'espada' ]: 9,
//     [ 11, 'basto' ]: 9,
//     [ 11, 'oro' ]: 9,
//     [ 11, 'copa' ]: 9,
//     [ 10, 'espada' ]: 10,
//     [ 10, 'basto' ]: 10,
//     [ 10, 'oro' ]: 10,
//     [ 10, 'copa' ]: 10,
//     [ 7, 'basto' ]: 11,
//     [ 7, 'copa' ]: 11,
//     [ 6, 'espada' ]: 12,
//     [ 6, 'basto' ]: 12,
//     [ 6, 'oro' ]: 12,
//     [ 6, 'copa' ]: 12,
//     [ 5, 'espada' ]: 13,
//     [ 5, 'basto' ]: 13,
//     [ 5, 'oro' ]: 13,
//     [ 5, 'copa' ]: 13,
//     [ 4, 'espada' ]: 14,
//     [ 4, 'basto' ]: 14,
//     [ 4, 'oro' ]: 14,
//     [ 4, 'copa' ]: 14,
// }
// const SampleDeck = {
//     [ 1, 'espada' ]: 1,
//     [ 1, 'basto' ]: 2,
//     [ 7, 'espada' ]: 3,
//     [ 7, 'oro' ]: 4,
//     [ 3, 'espada' ]: 5,
//     [ 3, 'basto' ]: 5,
//     [ 3, 'oro' ]: 5,
//     [ 3, 'copa' ]: 5,
//     [ 2, 'espada' ]: 6,
//     [ 2, 'basto' ]: 6,
//     [ 2, 'oro' ]: 6,
//     [ 2, 'copa' ]: 6,
//     [ 1, 'oro' ]: 7,
//     [ 1, 'copa' ]: 7,
//     [ 12, 'espada' ]: 8,
//     [ 12, 'basto' ]: 8,
//     [ 12, 'oro' ]: 8,
//     [ 12, 'copa' ]: 8,
//     [ 11, 'espada' ]: 9,
//     [ 11, 'basto' ]: 9,
//     [ 11, 'oro' ]: 9,
//     [ 11, 'copa' ]: 9,
//     [ 10, 'espada' ]: 10,
//     [ 10, 'basto' ]: 10,
//     [ 10, 'oro' ]: 10,
//     [ 10, 'copa' ]: 10,
//     [ 7, 'basto' ]: 11,
//     [ 7, 'copa' ]: 11,
//     [ 6, 'espada' ]: 12,
//     [ 6, 'basto' ]: 12,
//     [ 6, 'oro' ]: 12,
//     [ 6, 'copa' ]: 12,
//     [ 5, 'espada' ]: 13,
//     [ 5, 'basto' ]: 13,
//     [ 5, 'oro' ]: 13,
//     [ 5, 'copa' ]: 13,
//     [ 4, 'espada' ]: 14,
//     [ 4, 'basto' ]: 14,
//     [ 4, 'oro' ]: 14,
//     [ 4, 'copa' ]: 14,
// }
// const SampleDeck1 = [ 
//     [ 1, 'espada' ],
//     [ 1, 'basto' ],
//     [ 7, 'espada' ],
//     [ 7, 'oro' ],
//     [ 3, 'espada' ],
//     [ 3, 'basto' ],
//     [ 3, 'oro' ],
//     [ 3, 'copa' ],
//     [ 2, 'espada' ],
//     [ 2, 'basto' ],
//     [ 2, 'oro' ],
//     [ 2, 'copa' ],
//     [ 1, 'oro' ],
//     [ 1, 'copa' ],
//     [ 12, 'espada' ],
//     [ 12, 'basto' ],
//     [ 12, 'oro' ],
//     [ 12, 'copa' ],
//     [ 11, 'espada' ],
//     [ 11, 'basto' ],
//     [ 11, 'oro' ],
//     [ 11, 'copa' ],
//     [ 10, 'espada' ],
//     [ 10, 'basto' ],
//     [ 10, 'oro' ],
//     [ 10, 'copa' ],
//     [ 7, 'basto' ],
//     [ 7, 'copa' ],
//     [ 6, 'espada' ],
//     [ 6, 'basto' ],
//     [ 6, 'oro' ],
//     [ 6, 'copa' ],
//     [ 5, 'espada' ],
//     [ 5, 'basto' ],
//     [ 5, 'oro' ],
//     [ 5, 'copa' ],
//     [ 4, 'espada' ],
//     [ 4, 'basto' ],
//     [ 4, 'oro' ],
//     [ 4, 'copa' ],
// ]
// const SampleDeck1 = [ 
//     [[ 1, 'espada' ]],
//     [[ 1, 'basto' ]],
//     [[ 7, 'espada' ]],
//     [[ 7, 'oro' ]],
//     [[ 3, 'espada' ],
//     [ 3, 'basto' ],
//     [ 3, 'oro' ],
//     [ 3, 'copa' ]],
//     [[ 2, 'espada' ],
//     [ 2, 'basto' ],
//     [ 2, 'oro' ],
//     [ 2, 'copa' ]],
//     [[ 1, 'oro' ],
//     [ 1, 'copa' ]],
//     [[ 12, 'espada' ],
//     [ 12, 'basto' ],
//     [ 12, 'oro' ],
//     [ 12, 'copa' ]],
//     [[ 11, 'espada' ],
//     [ 11, 'basto' ],
//     [ 11, 'oro' ],
//     [ 11, 'copa' ]],
//     [[ 10, 'espada' ],
//     [ 10, 'basto' ],
//     [ 10, 'oro' ],
//     [ 10, 'copa' ]],
//     [[ 7, 'basto' ],
//     [ 7, 'copa' ]],
//     [[ 6, 'espada' ],
//     [ 6, 'basto' ],
//     [ 6, 'oro' ],
//     [ 6, 'copa' ]],
//     [[ 5, 'espada' ],
//     [ 5, 'basto' ],
//     [ 5, 'oro' ],
//     [ 5, 'copa' ]],
//     [[ 4, 'espada' ],
//     [ 4, 'basto' ],
//     [ 4, 'oro' ],
//     [ 4, 'copa' ]],
// ]
